[package]
name = "senaling-core"
edition.workspace = true
version.workspace = true
build = "build.rs"

[dependencies]
csv = "1.4.0"
anyhow.workspace = true
log.workspace = true

[lib]
name = "senaling_core"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.29.4"
anyhow.workspace = true
